sql_execute create unique index i_i_id on item (i_id asc)
sql_execute create unique index i_o_id on orders (o_id asc)
sql_execute create unique index i_c_id on customer (c_id asc)
sql_execute create unique index i_addr_id on address (addr_id asc)
sql_execute create unique index i_co_id on country (co_id asc)
sql_execute create unique index i_cx_o_id on cc_xacts (cx_o_id asc)
sql_execute create unique index i_a_id on author (a_id asc)
sql_execute create unique index i_ol_id_ol_o_id on order_line ( ol_id, ol_o_id )

sql_execute create unique index i_sc_id on shopping_cart (sc_id asc)
sql_execute create unique index i_scl_sc_id_scl_i_id on shopping_cart_line ( scl_sc_id, scl_i_id )

sql_execute create index i_c_uname on customer (c_uname asc)
sql_execute create index i_o_c_id on orders (o_c_id asc)
sql_execute create index i_ol_o_id on order_line (ol_o_id desc)
sql_execute create index i_ol_i_id on order_line (ol_i_id asc)
sql_execute create index i_address_table on address (addr_street1, addr_street2, addr_city, addr_state, addr_zip, addr_co_id)
sql_execute create index i_i_subject on item (i_subject asc)
sql_execute create index i_i_title on item (i_title asc)
sql_execute create index i_i_a_id on item (i_a_id asc)
sql_execute create index i_a_lname on author (a_lname asc)
