sql_execute drop table item 
sql_execute drop table country
sql_execute drop table author
sql_execute drop table customer
sql_execute drop table orders
sql_execute drop table order_line
sql_execute drop table cc_xacts
sql_execute drop table address
sql_execute drop table shopping_cart
sql_execute drop table shopping_cart_line
