sql_execute drop dbproc getPromoImages
sql_execute drop dbproc DigSyl
sql_execute drop dbproc getSCSubTotal
sql_execute drop dbproc addToSC
sql_execute drop dbproc createSC
sql_execute drop dbproc refreshSC
sql_execute drop dbproc getCustInfo
sql_execute drop dbproc InsertCust
sql_execute drop dbproc updateSC
sql_execute drop dbproc initSCItems
sql_execute drop dbproc getSCDetail
sql_execute drop dbproc initOrderItems
sql_execute drop dbproc getOrderItems
sql_execute drop dbproc home
sql_execute drop dbproc buy_request
sql_execute drop dbproc buy_confirm
sql_execute drop dbproc shopping_cart
sql_execute drop dbproc order_inquiry
sql_execute drop dbproc order_display
sql_execute drop dbproc product_detail
sql_execute drop dbproc admin_request
sql_execute drop dbproc admin_confirm
sql_execute drop dbproc new_products
sql_execute drop dbproc best_sellers
sql_execute drop dbproc search_results_author
sql_execute drop dbproc search_results_subject
sql_execute drop dbproc search_results_title
