sql_execute update statistics item
sql_execute update statistics country
sql_execute update statistics author
sql_execute update statistics customer
sql_execute update statistics orders
sql_execute update statistics order_line
sql_execute update statistics cc_xacts
sql_execute update statistics address
sql_execute update statistics shopping_cart
sql_execute update statistics shopping_cart_line
