#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
#

if [ "x${DBNAME}" = "x" ]; then
	echo "DBNAME not defined."
	exit 1
fi

while getopts "l:" OPT; do
        case ${OPT} in
        l)
                PORT=${OPTARG}
                ;;
        esac
done

if [ ! "x${PORT}" = "x" ]; then
        PORTARG="-p ${PORT}"
fi
PSQL="psql ${PORTARG} -d ${DBNAME}"

echo "Checking dbt1 database '${DBNAME}'..."
echo

# Load tables
echo author
${PSQL} -c "select count(*) from author"
echo country
${PSQL} -c "select count(*) from country"
echo address
${PSQL} -c "select count(*) from address"
echo customer
${PSQL} -c "select count(*) from customer"
echo item
${PSQL} -c "select count(*) from item"
echo orders
${PSQL} -c "select count(*) from orders"
echo order_line
${PSQL} -c "select count(*) from order_line"
echo cc_xacts
${PSQL} -c "select count(*) from cc_xacts"
echo shopping_cart
${PSQL} -c "select count(*) from shopping_cart"
echo shopping_cart_line
${PSQL} -c "select count(*) from shopping_cart_line"
