#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labss, Inc.
#

if [ -z ${DBNAME} ]; then
    echo "DBNAME not defined."
    exit 1
fi

USE_TABLESPACES=0
while getopts "l:t" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi
PSQL="psql ${PORTARG} -e -d ${DBNAME}"

if [ ${USE_TABLESPACES} -eq 1 ]; then
	if [ "x${DBT2TSDIR}" = "x" ]; then
		echo "DBT2TSDIR is not set."
		exit 1
	fi
	TS_WAREHOUSE_DIR=${DBT2TSDIR}/warehouse/ts
	TS_DISTRICT_DIR=${DBT2TSDIR}/district/ts
	TS_CUSTOMER_DIR=${DBT2TSDIR}/customer/ts
	TS_HISTORY_DIR=${DBT2TSDIR}/history/ts
	TS_NEW_ORDER_DIR=${DBT2TSDIR}/new_order/ts
	TS_ORDERS_DIR=${DBT2TSDIR}/orders/ts
	TS_ORDER_LINE_DIR=${DBT2TSDIR}/order_line/ts
	TS_ITEM_DIR=${DBT2TSDIR}/item/ts
	TS_STOCK_DIR=${DBT2TSDIR}/stock/ts

	#
	# Creating 'ts' subdirectories because PostgreSQL doesn't like that
	# 'lost+found' directory if a device was mounted at
	# '${DBT2TSDIR}/warehouse'.
	#
	mkdir -p ${TS_WAREHOUSE_DIR} || exit 1
	mkdir -p ${TS_DISTRICT_DIR} || exit 1
	mkdir -p ${TS_CUSTOMER_DIR} || exit 1
	mkdir -p ${TS_HISTORY_DIR} || exit 1
	mkdir -p ${TS_NEW_ORDER_DIR} || exit 1
	mkdir -p ${TS_ORDERS_DIR} || exit 1
	mkdir -p ${TS_ORDER_LINE_DIR} || exit 1
	mkdir -p ${TS_ITEM_DIR} || exit 1
	mkdir -p ${TS_STOCK_DIR} || exit 1

	TS_WAREHOUSE="TABLESPACE dbt2_warehouse"
	TS_DISTRICT="TABLESPACE dbt2_district"
	TS_CUSTOMER="TABLESPACE dbt2_customer"
	TS_HISTORY="TABLESPACE dbt2_history"
	TS_NEW_ORDER="TABLESPACE dbt2_new_order"
	TS_ORDERS="TABLESPACE dbt2_orders"
	TS_ORDER_LINE="TABLESPACE dbt2_order_line"
	TS_ITEM="TABLESPACE dbt2_item"
	TS_STOCK="TABLESPACE dbt2_stock"

	#
	# Don't need to '|| exit 1' in case the tablespaces do not already exist.
	#
	${PSQL} -c "DROP ${TS_WAREHOUSE};"
	${PSQL} -c "CREATE ${TS_WAREHOUSE} LOCATION '${TS_WAREHOUSE_DIR}';"
	${PSQL} -c "DROP ${TS_DISTRICT};"
	${PSQL} -c "CREATE ${TS_DISTRICT} LOCATION '${TS_DISTRICT_DIR}';"
	${PSQL} -c "DROP ${TS_CUSTOMER};"
	${PSQL} -c "CREATE ${TS_CUSTOMER} LOCATION '${TS_CUSTOMER_DIR}';"
	${PSQL} -c "DROP ${TS_HISTORY};"
	${PSQL} -c "CREATE ${TS_HISTORY} LOCATION '${TS_HISTORY_DIR}';"
	${PSQL} -c "DROP ${TS_NEW_ORDER};"
	${PSQL} -c "CREATE ${TS_NEW_ORDER} LOCATION '${TS_NEW_ORDER_DIR}';"
	${PSQL} -c "DROP ${TS_ORDERS};"
	${PSQL} -c "CREATE ${TS_ORDERS} LOCATION '${TS_ORDERS_DIR}';"
	${PSQL} -c "DROP ${TS_ORDER_LINE};"
	${PSQL} -c "CREATE ${TS_ORDER_LINE} LOCATION '${TS_ORDER_LINE_DIR}';"
	${PSQL} -c "DROP ${TS_ITEM};"
	${PSQL} -c "CREATE ${TS_ITEM} LOCATION '${TS_ITEM_DIR}';"
	${PSQL} -c "DROP ${TS_STOCK};"
	${PSQL} -c "CREATE ${TS_STOCK} LOCATION '${TS_STOCK_DIR}';"
fi

${PSQL} -c "
begin;
create table author ( a_id numeric(10), a_fname varchar(20), a_lname varchar(20), a_mname varchar(20), a_dob date, a_bio varchar(500), primary key (a_id) );

create table country ( co_id numeric(4), co_name varchar(50), co_exchange numeric(12, 6), co_currency varchar(18), primary key (co_id) );

create table address ( addr_id numeric(10), addr_street1 varchar(40), addr_street2 varchar(40), addr_city varchar(30), addr_state varchar(20), addr_zip varchar(10), addr_co_id numeric(4), primary key (addr_id));

create table customer ( c_id numeric(10), c_uname varchar(20), c_passwd varchar(20), c_fname varchar(15), c_lname varchar(15), c_addr_id numeric(10), c_phone varchar(16), c_email varchar(50), c_since date, c_last_visit date, c_login timestamp, c_expiration timestamp, c_discount numeric(5, 2), c_balance numeric(17, 2), c_ytd_pmt numeric(17, 2), c_birthdate date, c_data varchar(500), primary key (c_id));

create table item ( i_id numeric(10), i_title varchar(60), i_a_id numeric(10), i_pub_date date, i_publisher varchar(60), i_subject varchar(60), i_desc varchar(500), i_related1 numeric(10), i_related2 numeric(10), i_related3 numeric(10), i_related4 numeric(10), i_related5 numeric(10), i_thumbnail numeric(8), i_image numeric(8), i_srp numeric(17, 2), i_cost numeric(17, 2), i_avail date, i_stock numeric(4), i_isbn char(13), i_page numeric(4), i_backing varchar(15), i_dimensions varchar(25), primary key (i_id));

create table orders ( o_id numeric(10), o_c_id numeric(10), o_date timestamp, o_sub_total numeric(17, 2), o_tax numeric(17, 2), o_total numeric(17, 2), o_ship_type varchar(10), o_ship_date timestamp, o_bill_addr_id numeric(10), o_ship_addr_id numeric(10), o_status varchar(15), primary key (o_id));

create table order_line ( ol_id numeric(3), ol_o_id numeric(10), ol_i_id numeric(10), ol_qty numeric(3), ol_discount numeric(5, 2), ol_comments varchar(100), primary key(ol_o_id, ol_id));

create table cc_xacts ( cx_o_id numeric(10), cx_type varchar(10), cx_num numeric(16), cx_name varchar(31), cx_expiry date, cx_auth_id char(15), cx_xact_amt numeric(17, 2), cx_xact_date timestamp, cx_co_id numeric(4), primary key (cx_o_id));

create table shopping_cart ( sc_id numeric(10), sc_c_id numeric(10), sc_date timestamp, sc_sub_total numeric(17, 2), sc_tax numeric(17, 2), sc_ship_cost numeric(17, 2), sc_total numeric(17, 2), sc_c_fname varchar(15), sc_c_lname varchar(15), sc_c_discount numeric(5, 2), primary key(sc_id) );

create table shopping_cart_line ( scl_sc_id numeric(10), scl_i_id numeric(10), scl_qty numeric(3), scl_cost numeric(17, 2), scl_srp numeric(17, 2), scl_title varchar(60), scl_backing varchar(15), primary key(scl_sc_id, scl_i_id) );

GRANT ALL PRIVILEGES ON TABLE address, author, cc_xacts, country, customer, item, order_line, orders, shopping_cart, shopping_cart_line TO PUBLIC;

commit;
" || exit 1

exit 0
