#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
#

USE_TABLESPACES=0
while getopts "l:t" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi

if [ -z ${DBNAME} ]; then
	echo "DBNAME not defined."
	exit 1
fi

PSQL="psql ${PORTARG} -e -d ${DBNAME}"

if [ ${USE_TABLESPACES} -eq 1 ]; then
	if [ "x${DBT2TSDIR}" = "x" ]; then
		echo "DBT2TSDIR is not set."
		exit 1
	fi
	TS_PK_WAREHOUSE_DIR="${DBT2TSDIR}/pk_warehouse/ts"
	TS_PK_DISTRICT_DIR="${DBT2TSDIR}/pk_district/ts"
	TS_PK_CUSTOMER_DIR="${DBT2TSDIR}/pk_customer/ts"
	TS_PK_NEW_ORDER_DIR="${DBT2TSDIR}/pk_new_order/ts"
	TS_PK_ORDERS_DIR="${DBT2TSDIR}/pk_orders/ts"
	TS_PK_ORDER_LINE_DIR="${DBT2TSDIR}/pk_order_line/ts"
	TS_PK_ITEM_DIR="${DBT2TSDIR}/pk_item/ts"
	TS_PK_STOCK_DIR="${DBT2TSDIR}/pk_stock/ts"
	TS_INDEX1_DIR="${DBT2TSDIR}/index1/ts"
	TS_INDEX2_DIR="${DBT2TSDIR}/index2/ts"

	#
	# Creating 'ts' subdirectories because PostgreSQL doesn't like that
	# 'lost+found' directory if a device was mounted at
	# '${DBT2TSDIR}/warehouse'.
	#
	mkdir -p ${TS_PK_WAREHOUSE_DIR} || exit 1
	mkdir -p ${TS_PK_DISTRICT_DIR} || exit 1
	mkdir -p ${TS_PK_CUSTOMER_DIR} || exit 1
	mkdir -p ${TS_PK_NEW_ORDER_DIR} || exit 1
	mkdir -p ${TS_PK_ORDERS_DIR} || exit 1
	mkdir -p ${TS_PK_ORDER_LINE_DIR} || exit 1
	mkdir -p ${TS_PK_ITEM_DIR} || exit 1
	mkdir -p ${TS_PK_STOCK_DIR} || exit 1
	mkdir -p ${TS_INDEX1_DIR} || exit 1
	mkdir -p ${TS_INDEX2_DIR} || exit 1

	TS_PK_WAREHOUSE="TABLESPACE dbt2_pk_warehouse"
	TS_PK_DISTRICT="TABLESPACE dbt2_pk_district"
	TS_PK_CUSTOMER="TABLESPACE dbt2_pk_customer"
	TS_PK_NEW_ORDER="TABLESPACE dbt2_pk_new_order"
	TS_PK_ORDERS="TABLESPACE dbt2_pk_orders"
	TS_PK_ORDER_LINE="TABLESPACE dbt2_pk_order_line"
	TS_PK_ITEM="TABLESPACE dbt2_pk_item"
	TS_PK_STOCK="TABLESPACE dbt2_pk_stock"
	TS_INDEX1="TABLESPACE dbt2_index1"
	TS_INDEX2="TABLESPACE dbt2_index2"

	#
	# Don't need to '|| exit 1' in case the tablespaces already exist.
	#
	${PSQL} -c "CREATE ${TS_PK_WAREHOUSE} LOCATION '${TS_PK_WAREHOUSE_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_DISTRICT} LOCATION '${TS_PK_DISTRICT_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_CUSTOMER} LOCATION '${TS_PK_CUSTOMER_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_NEW_ORDER} LOCATION '${TS_PK_NEW_ORDER_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_ORDERS} LOCATION '${TS_PK_ORDERS_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_ORDER_LINE} LOCATION '${TS_PK_ORDER_LINE_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_ITEM} LOCATION '${TS_PK_ITEM_DIR}';"
	${PSQL} -c "CREATE ${TS_PK_STOCK} LOCATION '${TS_PK_STOCK_DIR}';"
	${PSQL} -c "CREATE ${TS_INDEX1} LOCATION '${TS_INDEX1_DIR}';"
	${PSQL} -c "CREATE ${TS_INDEX2} LOCATION '${TS_INDEX2_DIR}';"

	#
	# Rewrite these variables for the actualy index creaxtion.
	#
	TS_PK_WAREHOUSE="USING INDEX ${TS_PK_WAREHOUSE}"
	TS_PK_DISTRICT="USING INDEX ${TS_PK_DISTRICT}"
	TS_PK_CUSTOMER="USING INDEX ${TS_PK_CUSTOMER}"
	TS_PK_NEW_ORDER="USING INDEX ${TS_PK_NEW_ORDER}"
	TS_PK_ORDERS="USING INDEX ${TS_PK_ORDERS}"
	TS_PK_ORDER_LINE="USING INDEX ${TS_PK_ORDER_LINE}"
	TS_PK_ITEM="USING INDEX ${TS_PK_ITEM}"
	TS_PK_STOCK="USING INDEX ${TS_PK_STOCK}"
fi

${PSQL} -c "
begin;
create index i_i_subject on item (i_subject);
create index i_i_a_id on item (i_a_id);
create index i_address_table on address (addr_street1, addr_street2, addr_city, addr_state, addr_zip, addr_co_id);
create index i_c_uname on customer (c_uname);
create index i_o_c_id on orders (o_c_id);
create index i_i_title on item (i_title);
create index i_a_lname on author (a_lname);
commit;
" || exit 1

${PSQL} -c "
begin;
alter table item add constraint fk_i_a_id foreign key ( i_a_id ) references author ( a_id );
alter table customer add constraint fk_c_addr_id foreign key ( c_addr_id ) references address ( addr_id );
alter table orders add constraint fk_o_c_id foreign key ( o_c_id ) references customer ( c_id );
alter table orders add constraint fk_o_bill_addr_id foreign key ( o_bill_addr_id ) references address ( addr_id );
alter table orders add constraint fk_o_ship_addr_id foreign key ( o_ship_addr_id ) references address ( addr_id );
alter table order_line add constraint fk_line_ol_i_id foreign key ( ol_i_id ) references item ( i_id );
alter table order_line add constraint fk_line_ol_o_id foreign key ( ol_o_id ) references orders ( o_id );
alter table cc_xacts add constraint fk_cx_o_id foreign key ( cx_o_id ) references orders ( o_id );
alter table cc_xacts add constraint fk_cx_co_id foreign key ( cx_co_id ) references country ( co_id );
alter table address add constraint fk_addr_co_id foreign key ( addr_co_id ) references country ( co_id );
commit;
" || exit 1

exit 0
