#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Mark Wong & Open Source Development Labs, Inc.
#

if [ "x${DBNAME}" = "x" ]; then
    echo "DBNAME not defined."
    exit 1
fi

while getopts "l:" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi
PSQL="psql ${PORTARG} -e -d ${DBNAME}"

# need to consider table dependencies.
${PSQL} -c "DROP TABLE shopping_cart_line;"
${PSQL} -c "DROP TABLE shopping_cart;"
${PSQL} -c "DROP TABLE cc_xacts;"
${PSQL} -c "DROP TABLE order_line;"
${PSQL} -c "DROP TABLE orders;"
${PSQL} -c "DROP TABLE customer;"
${PSQL} -c "DROP TABLE address;"
${PSQL} -c "DROP TABLE item;"
${PSQL} -c "DROP TABLE author;"
${PSQL} -c "DROP TABLE country;"
